# Use node 17.9 because 18.2 has an issue with setting the proxy hostname
FROM node:17.9

# Set working directory
USER node
WORKDIR /app
# Install app dependencies
COPY --chown=node:node package.json package-lock.json ./
RUN npm install

# Run the application in dev mode using react-scripts
COPY --chown=node:node . ./
CMD ["npm", "start"]