# Use a minimal base image
FROM node:18.2.0-alpine3.15

RUN npm install -g nodemon

USER node
WORKDIR /app

# Copy dependency information and install all dependencies
COPY  --chown=node:node package.json package-lock.json ./
RUN npm install

# Copy source code (and all other relevant files)
COPY  --chown=node:node . .

# Expose the application on port 5000
EXPOSE 5000
CMD [ "npm", "run", "dev"]
